### ISSUE TITLE
This is fun

### ISSUE THREAD

**Issue by danydacosta** [SteeveDroz/drive-alone#1]
After playing around here are my scores:

- My first car managed to finish the track in 56 generations. 
- The second one in 30 generations...

So weird how I can actually watch rectangles slide on my screen and not being bored even after 10 minutes. I noticed that the cars take more time to do the first turn that the others. 

How about adding a timer to see how long it takes to the cars to finish the track? And I think it would be nice if the program could run in the background (not only when the tab is active).

**Comment by SteeveDroz** [comment]
That was indeed my next idea about that.

**Comment by SteeveDroz** [comment]
New rules:

1. The car that goes the furthest is the best.
2. Amongst the cars that finished the track, the fastest is the best.

As for the background thing, I think it depends on the browser. You can still do it with a nice hack: open *Drive Alone* in another window instead of another tab.
